
name: Yuhang Chen

description: My Blogs

avatar: https://raw.githubusercontent.com/realcyh/yuhang-chen/master/images/mypic.jpeg

favicon: https://raw.githubusercontent.com/realcyh/yuhang-chen/master/images/Slide1.png


navigation:
  - name: Me
    url: /me
  - name: Blogs
    url: /
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links: 
  email: realcyh@outlook.com 
  facebook: yuhang.chen.50999
  linkedin: realcyh-yuhang-chen
  github: realcyh

footer-text: Copyright ©️ 2020 realcyh

baseurl: /yuhang-chen


#
# !! Do not change anything below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  
